---
- name: Fetch python-xcat3client from github
  git: repo="{{ xcat3_client_url }}"
       dest="{{ xcat3_client_path }}"

- name: Install python dependency for python-xcat3client project
  pip:
    requirements: "{{ xcat3_client_path }}/requirements.txt"

- name: Setup python-xcat3client with develop version( not complete)
  shell: python setup.py develop chdir="{{ xcat3_client_path }}"

- name: Create xCAT3 environment file
  template: src=templates/xcat3.sh dest=/etc/profile.d/xcat3.sh owner=root mode=0600

- name: Update bashrc for Python
  lineinfile:
    dest=/root/.bashrc
    line="source {{xcat3_client_path}}/tools/xcat3.bash_completion"
    state=present
    insertafter=EOF
    create=True