---
- name: Include ubuntu template to setup common roles
  include: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Include ubuntu template to setup common roles
  include: redhat.yml
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Fetch xcat3 from github
  git: repo="{{ xcat3_url }}"
       dest="{{ xcat3_path }}"

- name: Install python dependency for xcat3 project
  shell: |
    pypy -m pip install cryptography==1.8
    pypy -m pip install -r "{{ xcat3_path }}/requirements.txt"

- name: Patch _py3k_acquire threading.py
  replace:
    dest: "{{pypy_root}}/lib-python/2.7/threading.py"
    regexp: "_py3k_acquire"
    replace: "acquire"

- name: Setup xcat3 with develop version( not complete)
  shell: pypy setup.py develop chdir="{{ xcat3_path }}"

- name: Creates /etc/xcat3 directory
  file: path=/etc/xcat3 state=directory

- name: Creates /etc/xcat3 directory
  file: path=/var/log/xcat3 state=directory

- name: Creates xcat3 data directory
  file: path={{ xcat3_data_dir }} state=directory

- name: Create xCAT3 configuration file
  template: src=templates/xcat3.conf dest=/etc/xcat3/xcat3.conf owner=root mode=0600