---
# Handler to handle DB tier notifications

- name: restart mysql
  service: name=mysql state=restarted
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: restart mariadb
  systemd:
    state: restarted
    daemon_reload: yes
    name: mariadb
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_version|int >=7

- name: Reload firewalld configuration
  shell: firewall-cmd --reload
  ignore_errors: True
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_version|int >=7