---
# Handler to handle conductor notifications

- name: Restart apache24
  service: name=apache2 state=restarted
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Restart xinetd service on Ubuntu
  service:
    name: xinetd
    state: restarted
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Restart httpd
  systemd: name=httpd state=restarted daemon_reload=yes
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Restart xinetd service on Redhat
  systemd:
    name: xinetd
    state: restarted
    daemon_reload: yes
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Reload firewalld configuration
  shell: firewall-cmd --reload
  ignore_errors: True
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_version|int >=7