---
- name: Create rpm cache directory
  file: path=/tmp/cache state=directory

- name: Enable epel yum repo
  copy: src="{{ item }}" dest=/tmp/cache
  with_items:
    - "{{ epel_rpm }}"

- name: Setup epel yum repo
  yum: name={{ item }} state=present
  with_items:
    - "/tmp/cache/{{ epel_rpm }}"
  ignore_errors: True

- name: Install rabbitmq rpm packages
  yum: name={{ item }} state=latest
  with_items:
    - rabbitmq-server

# rabbitmq do not start automatically
- name: Start RabbitMq Server
  systemd:
    state: started
    daemon_reload: yes
    name: rabbitmq-server
