---
galaxy_info:
  author: xCAT Developers
  description: Install xCAT on localhost
  min_ansible_version: 1.9
  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - utopic
  categories:
  - cloud
dependencies: []
