---
- name: Install dhcp packages
  apt: name={{item}} state=latest
  with_items:
    - isc-dhcp-server
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install dhcp packages
  yum: name={{item}} state=latest
  with_items:
    - dhcp
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS'

- name: Stop xcat3-network service if exist
  shell: pkill xcat3-network
  ignore_errors: True

- name: Start xcat3-network daemon
  shell: nohup xcat3-network --config-file /etc/xcat3/xcat3.conf &
