---
- name: Get go-xcat scripts from xcat org
  get_url:
    url: "{{ go_xcat_url }}"
    dest: /tmp/go-xcat
    validate_certs: False

- name: Add execution permission for go-xcat script
  file: path=/tmp/go-xcat mode=u+x

- name: Test xcat installed or not
  stat: path={{ xcatd_path }}
  register: xcatd_file_status
  ignore_errors: True

- name: Running go-xcat to install xcat
  become: true
  script: /tmp/go-xcat "-y" "install"
  when: not xcatd_file_status.stat.exists

- name: Check xcat version
  become: true
  xcat_cmd:
    command: lsdef
    options:
      "--version": ""
  register: xcat_version

- name: "Abort due to failure of xcat installation"
  fail: >
    msg="xcat setup failed"
  when: xcat_version.rc != 0

- include: config.yml
