---
- name: Disable selinux configuration
  lineinfile:
    path: /etc/selinux/config
    regexp: 's/^SELINUX=.*$'
    line: 'SELINUX=disabled'

- name: Disable selinux
  shell: setenforce 0

- name: Stop firewalld
  systemd:
    state: stopped
    name: firewalld
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_version|int >=7

- name: Install rpm packages
  yum: name={{ item }} state=latest
  with_items:
    - python-devel
    - openssl-devel
    - mysql-devel
    - libxml2-devel
    - libxslt-devel
    - postgresql-devel
    - git
    - libffi-devel
    - gettext
    - python-setuptools
    - gcc

- name: Create pip cache directory
  file: path=/tmp/cache state=directory

- name: Copy cache files for pip installation(Test local installation)
  copy: src="{{ item }}" dest=/tmp/cache
  with_items:
    - "{{ file_get_pip }}"
    - "{{ file_pip }}"
    - "{{ file_wheel }}"

- name: Setup pip with get-pip scripts
  shell: python get-pip.py --no-index --find-links=/tmp/cache chdir=/tmp/cache