---
# Handler to handle DB tier notifications

- name: Reload firewalld configuration
  shell: firewall-cmd --reload
  ignore_errors: True
  when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_version|int >=7